import type { DisclaimerDoc } from './disclaimer'

export const disclaimerEn: DisclaimerDoc = {
  intro: [
    'This Disclaimer applies to the Chaya open-source software and its related website, plugins and documentation (collectively, the “Tool”). “Developers” means the authors and contributors of the Tool. The Tool is provided free of charge by the Developers as open source and offers only technical features such as translation, editing and AI assistance.',
    'By downloading, installing, accessing or otherwise using the Tool, you acknowledge that you have read, understood and agree to be bound by this Disclaimer in its entirety. If you do not agree with any provision, stop using the Tool immediately and delete it.',
  ],
  sections: [
    {
      id: 'nature',
      title: 'Nature of the Tool',
      items: [
        'The Tool is a neutral technical tool. Except for third-party services you choose to use, its features run on your own device against games you select. The Developers do not provide, host, sell or distribute any game, game asset, translation or derivative thereof.',
        'The Tool is not affiliated with, authorized, approved or endorsed by Gotcha Gotcha Games, KADOKAWA Corporation, or any game author or publisher.',
        '“RPG Maker”, “RPGツクール” and related names and marks are trademarks of their respective owners and are used solely in a nominative manner to describe compatibility.',
      ],
    },
    {
      id: 'terms',
      title: 'Lawful use and the terms of each work',
      items: [
        'You shall use the Tool only with games you have lawfully obtained and in compliance with the laws and regulations of your jurisdiction.',
        'Before use, you shall review and comply with the documentation and license terms of the relevant work and the rules of its distribution platform (including but not limited to DLsite and Steam). Where the rights holder expressly prohibits translation, modification, analysis or any other secondary use, you shall not use the Tool on that work.',
        'You are solely responsible for confirming that your use is authorized by the rights holder or otherwise permitted by applicable law. You bear all consequences of any breach of a work’s terms or of applicable law.',
      ],
    },
    {
      id: 'translation',
      title: 'Translation and imported data',
      items: [
        'Translations generated with the Tool are solely for your personal study and understanding of the game’s content.',
        'Machine and AI translations may contain errors or inaccuracies and do not represent the original author’s intent. The Developers make no warranty as to the accuracy, completeness or fitness of any translation.',
        'The Tool allows you to import translation data you have obtained yourself. The Developers neither provide nor review any such data. You shall ensure it comes from a lawful source with any necessary authorization, and you bear all consequences of importing it.',
      ],
    },
    {
      id: 'distribution',
      title: 'No distribution services',
      items: [
        'The Developers do not provide any distribution, hosting, upload, sharing or download service of any kind, including but not limited to for game files, translation patches, translation caches, translated data files (including JSON and similar formats) and modified games.',
        'All data generated by the Tool is stored only on your local device. The Developers have no ability to access, control or review it.',
        'The Tool stores translation caches, plugins and other files in the game folder and in its local data folder. Before providing game files to anyone, you shall make sure they do not contain such files.',
        'You shall not publish, transmit, share, sell or otherwise make available to any third party any translation or modified game content without authorization from the rights holder. If you publicly display translations or modified game footage through live streams, videos, screenshots or similar means, you shall comply with the rights holder’s applicable rules.',
        'Any distribution or public display you carry out is your own independent act and is unrelated to the Developers. You alone bear all resulting liability for infringement, legal disputes and any other consequences.',
      ],
    },
    {
      id: 'third-party',
      title: 'Third-party services',
      items: [
        'When you choose to use third-party services such as Google, Bing or cloud AI, the game text to be processed (and, for AI assistant features, possibly screenshots) is transmitted to that provider and is governed by its terms of service, usage policies and privacy policy. The provider may store or use the content it receives in accordance with its policies.',
        'You are responsible for ensuring that the content you transmit complies with the third party’s usage policies. The Developers are not responsible for the availability, data handling or consequences of any third-party service.',
        'You manage and bear your own API keys, usage quotas and related costs. Local models (such as Ollama) run on your device and do not transmit text externally.',
      ],
    },
    {
      id: 'content',
      title: 'Game content',
      items: [
        'The Tool does not review the content of the games you select and is not responsible for its legality. Where a game contains adult or otherwise restricted content, you shall comply with the age-restriction and content laws of your jurisdiction.',
      ],
    },
    {
      id: 'edit',
      title: 'Editing, speed-up and save data',
      items: [
        'Features such as value editing, speed-up, teleport, and event and save editing operate only on the game process and save files on your local device.',
        'These features may cause malfunctions, corrupt saves or loss of progress. You shall make your own backups before use and bear any loss arising from their use.',
        'You shall not use these features in online play, multiplayer, leaderboards, achievement systems or any other context that may affect the rights of third parties or breach a work’s terms.',
      ],
    },
    {
      id: 'protection',
      title: 'Technical protection measures',
      items: [
        'The Tool does not provide, and will not add, any feature for circumventing technical protection measures, such as decrypting protected assets, cracking encrypted saves, bypassing activation or digital rights management (DRM), or unlocking paid content.',
        'You shall not use the Tool in combination with any means of circumventing technical protection measures.',
      ],
    },
    {
      id: 'install',
      title: 'Writing to the game folder',
      items: [
        'Installing the plugin or unified shell writes or replaces files in the game folder, which may conflict with a work’s terms or anti-tamper mechanisms. You are responsible for confirming that doing so is lawful and appropriate.',
        'The plugin may be uninstalled at any time. You shall back up the game folder before modifying it.',
      ],
    },
    {
      id: 'software',
      title: 'Third-party software',
      items: [
        'Third-party software that the Tool obtains or provides to run games, such as NW.js, and the open-source components the Tool depends on are governed by their respective licenses, and all rights therein belong to their owners.',
      ],
    },
    {
      id: 'agent',
      title: 'AI assistant and external connections',
      items: [
        'The built-in AI assistant, and any external AI client you authorize to connect via MCP / WebMCP, can read game state and the screen and perform actions on your behalf. You shall connect only clients you trust.',
        'AI-generated content and actions may be erroneous or differ from expectations. The Developers accept no responsibility for their results.',
      ],
    },
    {
      id: 'security',
      title: 'Security',
      items: [
        'The Developers do not warrant that the Tool is free of defects or security vulnerabilities. If you expose the Tool’s services to a local network or the internet, enable debugging features (including arbitrary script execution) or connect external clients, you do so at your own risk.',
      ],
    },
    {
      id: 'privacy',
      title: 'Data and privacy',
      items: [
        'Translation caches, settings, logs, backups and other data produced by the desktop version are stored on your local device. The Developers do not upload your game files to the Developers’ servers.',
        'The online version reads and writes the game folder you select only after your authorization, locally within your browser, and does not upload file contents. Translation requests from the online version are sent directly by the game process on your device to the translation service you choose and do not pass through the Developers’ servers.',
        'The Developers will update this Disclaimer in advance of any change to these data practices.',
        'For a complete description of data handling, see the Privacy Policy.',
      ],
    },
    {
      id: 'warranty',
      title: 'Disclaimer of warranties and limitation of liability',
      items: [
        'The Tool is provided “as is”, without warranty of any kind, express or implied, including as to availability, accuracy, compatibility, security or fitness for a particular purpose.',
        'To the maximum extent permitted by applicable law, the Developers shall not be liable for any direct, indirect, incidental, special or consequential loss arising from the use of or inability to use the Tool, including but not limited to corrupted saves, data loss, account penalties and third-party claims.',
      ],
    },
    {
      id: 'indemnity',
      title: 'User responsibility and indemnification',
      items: [
        'You are solely and fully legally responsible for the manner in which you use the Tool, the works you use it on, and all resulting consequences.',
        'You shall indemnify and hold the Developers harmless from any third-party claim or other loss arising from your breach of this Disclaimer, a work’s terms or applicable law, including any unauthorized distribution of translations or modified content.',
      ],
    },
    {
      id: 'license',
      title: 'Relationship to the open-source license',
      items: [
        'The Tool’s source code is released under the MIT License. This Disclaimer supplements the terms governing use of the Tool and does not restrict the rights granted by the MIT License.',
        'Versions of the Tool modified or redistributed by third parties are not versions provided by the Developers, and the Developers accept no responsibility for them.',
        'For the open-source license of the Tool and its scope, see the Open-source License page.',
      ],
    },
    {
      id: 'rights',
      title: 'Notices from rights holders',
      items: [
        'A rights holder who believes that any feature of the Tool infringes its lawful rights may contact the Developers through the project’s GitHub Issues. The Developers will take reasonable measures upon verification.',
      ],
    },
    {
      id: 'misc',
      title: 'Miscellaneous',
      items: [
        'If any provision of this Disclaimer is held invalid or unenforceable, the remaining provisions remain in full force and effect.',
        'The Chinese version of this Disclaimer prevails; versions in other languages are provided for reference only.',
        'The Developers may amend this Disclaimer as necessary. Amendments take effect on the date they are published on this page. Your continued use of the Tool constitutes acceptance of the amended Disclaimer.',
      ],
    },
  ],
}
