import {
  LEGACY_PLUGIN_BOOST_NAMES,
  LEGACY_PLUGIN_EDIT_NAMES,
  LEGACY_PLUGIN_RUNTIME_NAMES,
  LEGACY_PLUGIN_TRANS_NAMES,
  PLUGIN_ENV_NAME,
  PLUGIN_LOADER_NAME,
  PRODUCT_DISPLAY_NAME,
} from '@/constants/brand'
import { TRACKED_PLUGINS } from '@/lib/game/types'

import type { PluginsJsEntry } from './plugins-parse'

/**
 * Env 置顶 → Loader → 游戏原插件。
 * 去掉 TRACKED / 旧品牌条目，避免与 Loader 重复执行。
 * 纯函数，可供 Node 注入与浏览器 FSA 共用。
 */
export function mergeLoaderPluginEntries(existing: PluginsJsEntry[], loaderEntry: PluginsJsEntry): PluginsJsEntry[] {
  const dropNames = new Set<string>([
    PLUGIN_LOADER_NAME,
    ...TRACKED_PLUGINS,
    ...LEGACY_PLUGIN_RUNTIME_NAMES,
    ...LEGACY_PLUGIN_TRANS_NAMES,
    ...LEGACY_PLUGIN_EDIT_NAMES,
    ...LEGACY_PLUGIN_BOOST_NAMES,
  ])
  const prevEnv = existing.find((p) => p?.name === PLUGIN_ENV_NAME)
  const rest = existing.filter((p) => p && p.name !== PLUGIN_ENV_NAME && !dropNames.has(String(p.name)))

  const prevLoader = existing.find((p) => p?.name === PLUGIN_LOADER_NAME)
  const loader = {
    ...(prevLoader || {}),
    ...loaderEntry,
    status: true,
    parameters: (prevLoader?.parameters as Record<string, unknown> | undefined) ?? loaderEntry.parameters ?? {},
  }

  const env = {
    ...(prevEnv || {}),
    name: PLUGIN_ENV_NAME,
    status: true,
    description: prevEnv?.description || `${PRODUCT_DISPLAY_NAME} API 根（自动生成，供插件连服务）`,
    parameters: (prevEnv?.parameters as Record<string, unknown> | undefined) || {},
  }

  return [env, loader, ...rest]
}

/** 生成 ChayaEnv.js 正文（纯函数） */
export function buildChayaEnvJs(apiBase: string, opts?: { launchToken?: string; gameId?: string }): string {
  const base = apiBase.replace(/\/$/, '')
  const token = String(opts?.launchToken || '').trim()
  const gameId = String(opts?.gameId || '').trim()
  return `/* auto-generated by ${PRODUCT_DISPLAY_NAME} — do not edit by hand */
;(function () {
  try {
    window.CHAYA_API_BASE = ${JSON.stringify(base)}
    window.CHAYA_LOG_URL = ${JSON.stringify(`${base}/api/logs`)}
    ${token ? `window.CHAYA_LAUNCH_TOKEN = ${JSON.stringify(token)}` : 'try { delete window.CHAYA_LAUNCH_TOKEN } catch (e) {}'}
    ${gameId ? `window.CHAYA_GAME_ID = ${JSON.stringify(gameId)}` : 'try { delete window.CHAYA_GAME_ID } catch (e) {}'}
  } catch (e) {}
})()
`
}
