import {
  LEGACY_PLUGIN_BOOST_NAMES,
  LEGACY_PLUGIN_EDIT_NAMES,
  LEGACY_PLUGIN_RUNTIME_NAMES,
  LEGACY_PLUGIN_TRANS_NAMES,
  PLUGIN_ENV_NAME,
  PLUGIN_LOADER_NAME,
  PRODUCT_DISPLAY_NAME,
} from '@/constants/brand'
import { TRACKED_PLUGINS } from '@/lib/game/types'

import type { PluginsJsEntry } from './plugins-parse'

/**
 * Env 置顶 → Loader → 游戏原插件。
 * 去掉 TRACKED / 旧品牌条目，避免与 Loader 重复执行。
 * 纯函数，可供 Node 注入与浏览器 FSA 共用。
 */
export function mergeLoaderPluginEntries(existing: PluginsJsEntry[], loaderEntry: PluginsJsEntry): PluginsJsEntry[] {
  const dropNames = new Set<string>([
    PLUGIN_LOADER_NAME,
    ...TRACKED_PLUGINS,
    ...LEGACY_PLUGIN_RUNTIME_NAMES,
    ...LEGACY_PLUGIN_TRANS_NAMES,
    ...LEGACY_PLUGIN_EDIT_NAMES,
    ...LEGACY_PLUGIN_BOOST_NAMES,
  ])
  const prevEnv = existing.find((p) => p?.name === PLUGIN_ENV_NAME)
  const rest = existing.filter((p) => p && p.name !== PLUGIN_ENV_NAME && !dropNames.has(String(p.name)))

  const prevLoader = existing.find((p) => p?.name === PLUGIN_LOADER_NAME)
  const loader = {
    ...(prevLoader || {}),
    ...loaderEntry,
    status: true,
    parameters: (prevLoader?.parameters as Record<string, unknown> | undefined) ?? loaderEntry.parameters ?? {},
  }

  const env = {
    ...(prevEnv || {}),
    name: PLUGIN_ENV_NAME,
    status: true,
    description: prevEnv?.description || `${PRODUCT_DISPLAY_NAME} API 根（自动生成，供插件连服务）`,
    parameters: (prevEnv?.parameters as Record<string, unknown> | undefined) || {},
  }

  return [env, loader, ...rest]
}

function envAssign(name: string, value: string): string {
  return value ? `window.${name} = ${JSON.stringify(value)}` : `try { delete window.${name} } catch (e) {}`
}

export type ChayaEnvOptions = {
  launchToken?: string
  gameId?: string
  /** 浏览器模式信令令牌（见 `GAME_LINK_TOKEN_HEADER`） */
  linkToken?: string
  /** `link`：日志只经游戏连接发给页面，不上报服务器（浏览器模式） */
  logTransport?: 'http' | 'link'
}

/** 生成 ChayaEnv.js 正文（纯函数） */
export function buildChayaEnvJs(apiBase: string, opts?: ChayaEnvOptions): string {
  const base = apiBase.replace(/\/$/, '')
  const viaLink = opts?.logTransport === 'link'
  return `/* auto-generated by ${PRODUCT_DISPLAY_NAME} — do not edit by hand */
;(function () {
  try {
    window.CHAYA_API_BASE = ${JSON.stringify(base)}
    ${envAssign('CHAYA_LOG_URL', viaLink ? '' : `${base}/api/logs`)}
    ${envAssign('CHAYA_LOG_TRANSPORT', viaLink ? 'link' : '')}
    ${envAssign('CHAYA_LAUNCH_TOKEN', String(opts?.launchToken || '').trim())}
    ${envAssign('CHAYA_GAME_ID', String(opts?.gameId || '').trim())}
    ${envAssign('CHAYA_LINK_TOKEN', String(opts?.linkToken || '').trim())}
  } catch (e) {}
})()
`
}
